server:
  port : 8077

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:parkinglot
    username: Karol
    password: Karol@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true